# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\PROGRAMMING\APPLICATION PROJECTS\SImple To-Do List Application\SImple To-Do List Application [GUI - UI]\index.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GUI.todoListAppIcons import *

class Ui_indexWindow(object):
    def setupUi(self, indexWindow):
        indexWindow.setObjectName("indexWindow")
        indexWindow.resize(1366,768)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        indexWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\PROGRAMMING\\APPLICATION PROJECTS\\SImple To-Do List Application\\SImple To-Do List Application [GUI - UI]\\icons/todolist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        indexWindow.setWindowIcon(icon)
        indexWindow.setStyleSheet("background-color: rgb(57, 62, 70);")
        self.centralwidget = QtWidgets.QWidget(indexWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonIndexSignup = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonIndexSignup.sizePolicy().hasHeightForWidth())
        self.pushButtonIndexSignup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(35)
        self.pushButtonIndexSignup.setFont(font)
        self.pushButtonIndexSignup.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"color: rgb(34, 40, 49);")
        self.pushButtonIndexSignup.setObjectName("pushButtonIndexSignup")
        self.verticalLayout.addWidget(self.pushButtonIndexSignup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButtonIndexLogin = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(35)
        self.pushButtonIndexLogin.setFont(font)
        self.pushButtonIndexLogin.setStyleSheet("background-color: rgb(255, 211, 105);\n"
"color: rgb(34, 40, 49);")
        self.pushButtonIndexLogin.setObjectName("pushButtonIndexLogin")
        self.verticalLayout.addWidget(self.pushButtonIndexLogin)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelIndexLogo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.labelIndexLogo.sizePolicy().hasHeightForWidth())
        self.labelIndexLogo.setSizePolicy(sizePolicy)
        self.labelIndexLogo.setStyleSheet("image: url(:/newPrefix/icons/todolist.png);")
        self.labelIndexLogo.setText("")
        self.labelIndexLogo.setObjectName("labelIndexLogo")
        self.gridLayout_4.addWidget(self.labelIndexLogo, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem7, 2, 0, 1, 1)
        self.labelIndexTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(35)
        self.labelIndexTitle.setFont(font)
        self.labelIndexTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelIndexTitle.setObjectName("labelIndexTitle")
        self.gridLayout_2.addWidget(self.labelIndexTitle, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        indexWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(indexWindow)
        QtCore.QMetaObject.connectSlotsByName(indexWindow)

    def retranslateUi(self, indexWindow):
        _translate = QtCore.QCoreApplication.translate
        indexWindow.setWindowTitle(_translate("indexWindow", "Simple To-do List App"))
        self.pushButtonIndexSignup.setText(_translate("indexWindow", "SIGN UP"))
        self.pushButtonIndexLogin.setText(_translate("indexWindow", "LOG IN"))
        self.labelIndexTitle.setText(_translate("indexWindow", "<html><head/><body><p align=\"center\">SIMPLE TO-DO LIST APPLICATION</p></body></html>"))
from GUI.todoListAppIcons import *


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    indexWindow = QtWidgets.QMainWindow()
    ui = Ui_indexWindow()
    ui.setupUi(indexWindow)
    indexWindow.show()
    sys.exit(app.exec_())
